name: ml_finance_teixeiradossantos

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas=2.2.6
  - numpy=2.2.6
  - scikit-learn=1.6.1
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - jupyterlab=4.4.2
  - ipykernel

  - pip:
      - yfinance=0.2.30
      - xgboost=3.2.0
      - lightgbm=4.6.0
      - shap=0.48.0
      - mlflow=3.1.0
      - python-dotenv=1.1.0